'use strict';
const assert = require('node:assert/strict');
const fs = require('fs');
const source = fs.readFileSync('v2-music.js', 'utf8');
const mapHtml = fs.readFileSync('v2-map-practice.html', 'utf8');
const battleHtml = fs.readFileSync('v2-auto-battle-practice.html', 'utf8');
const mapJs = fs.readFileSync('v2-map-practice.js', 'utf8');
const battleJs = fs.readFileSync('v2-auto-battle-practice.js', 'utf8');
const worker = fs.readFileSync('service-worker.js', 'utf8');

assert(fs.statSync('assets/music/map-board.mp3').size > 1000000);
assert(fs.statSync('assets/music/battle.mp3').size > 1000000);
assert(source.includes('map-board.mp3') && source.includes('battle.mp3'));
assert(source.includes('music.loop = true') && source.includes('requestStart()'));
assert(source.includes('pointerdown') && source.includes('touchstart') && source.includes('pagehide'));
assert(source.includes('necromancer-v2-music-map-position'));
assert(source.includes('trackName === "map" && nextTrack === "battle"'));
assert(source.includes('applyPendingResume'));
assert(mapHtml.includes('data-v2-music="map"') && mapHtml.includes('src="v2-music.js?'));
assert(battleHtml.includes('data-v2-music="battle"') && battleHtml.includes('src="v2-music.js?'));
assert(mapJs.includes('V2Music.handoff("battle")'));
assert(battleJs.includes('V2Music.handoff("map")'));
assert(worker.includes('assets/music/map-board.mp3') && worker.includes('assets/music/battle.mp3'));
require('./scripts/assert-linked-cache')(mapHtml, worker, ['v2-music.js']);
require('./scripts/assert-linked-cache')(battleHtml, worker, ['v2-music.js']);
console.log('PASS: map and battle BGM files, mobile unlock, looping, and page handoff');
